[package]
name = "serana-tg"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "serana-tg"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
dotenvy = "0.15.7"
serana-adapters = { version = "0.1.0", path = "../serana-adapters" }
serana-domain = { version = "0.1.0", path = "../serana-domain" }
serana-services = { version = "0.1.0", path = "../serana-services" }
teloxide = "0.17.0"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[dev-dependencies]
serana-testkit = { path = "../serana-testkit" }
wiremock = "0.6.5"
